name: apply-bureau-backend
services:
- name: backend
  source_dir: /
  github:
    repo: Applybureau/AB-WEB
    branch: main
  run_command: cd backend && npm start
  build_command: cd backend && npm install
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"